### ISSUE TITLE
Decryption doesn't work

### ISSUE THREAD

**Issue by ideascout** [davidgfnet/wireshark-whatsapp#21]
Hi David,

thanks for the plugin. It works well but unfortunately i can't get the decryption to work. I'm using the latest version from GitHub and tried it with traffic that i've captured while sending messages from Android to iOS (so it should be RC4). I also tried it with traffic that has been redirected to your wa_proxy. The proxy seems to work as it tells me that it sees AUTH requests an various WA packets. Also i'm using the correct password from my device.

The decryption option of your plugin is active. But in the packet details within Wireshark it gives me only the term "Crypted Payload". Am i doing anything wrong? Am I right in assuming that the decrypted message text should be displayed within the packet details?

**Comment by davidgfnet** [comment]
It may happen that you are not properly using wa_proxy. Post the first 3 TCP packets you see and I'll be able to tell you whether it's ok or not.

**Comment by ideascout** [comment]
Here we go: https://drive.google.com/file/d/0B_RMV4oFgetYeXRyWDdJdjR3RFU/view?usp=sharing

**Comment by davidgfnet** [comment]
You are not properly using wa_proxy. Just look at your "auth" frame, it contains a data blob, therefore it's impossible for wireshark to decrypt it. wa_proxy is not straightforward to use if you are not familiar with networking. Closing this since there is not problem at all with the dissector, but the input.
